name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push User Service
      uses: docker/build-push-action@v2
      with:
        context: ./user-service
        push: true
        tags: cpjr446/user-service:latest

    - name: Build and push Product Service
      uses: docker/build-push-action@v2
      with:
        context: ./product-service
        push: true
        tags: cpjr446/product-service:latest

    - name: Build and push Cart Service
      uses: docker/build-push-action@v2
      with:
        context: ./cart-service
        push: true
        tags: cpjr446/cart-service:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/cpvbox/Devops-T2
          git pull origin main
          docker-compose pull
          docker-compose up -d
